# Dizionario per le spiegazioni dei tag
tag_descriptions = {
    'DXS': 'start of transaction',
    'DXS 01': 'Communication ID (of sender)',
    'DXS 02': 'Functional Identifier',
    'DXS 03': 'Version',
    'ST': 'Start of Transmission Set',
    'ID1': 'vending machine',
    'ID1 01': 'Machine Serial Number',
    'ID1 02': 'Machine Model Number',
    'ID1 03': 'Machine Build Standard',
    'ID1 04': 'Machine Location',
    'ID1 05': 'User Defined Data',
    'ID1 06': 'Machine Asset Number',
    'ID1 07': 'DTS Level',
    'ID1 08': 'DTS Revision',
    'ID4': 'Decimal Point Position',
    'ID4 01': 'Decimal Point Position',
    'ID4 02': 'Numeric Currency Code',
    'ID4 03': 'Alphabetic Currency Code',
    'MA5': 'machine configuration',
    'MA5 01': 'Block Identifier',
    'MA5 02': 'Specific Configuration Data',
    'MA5 03': 'Optional Field #2',
    'MA5 04': 'Optional Field #3',
    'MA5 05': 'Optional Field #4',
    'MA5 06': 'Optional Field #5',
    'MA5 07': 'Optional Field #6',
    'MA5 08': 'Optional Field #7',
    'MA5 09': 'Optional Field #8',
    'MA5 10': 'Optional Field #9',
    'MA5 11': 'Optional Field #10',
    'CA1': 'Coin Mechanism',
    'CA2': 'Coin Mechanism',
    'CA3': 'Coin Mechanism',
    'CA4': 'Coin Mechanism',
    'CA5': 'Coin Mechanism',
    'CA7': 'Coin Mechanism',
    'CA8': 'Coin Mechanism',
    'CA9': 'Coin Mechanism',
    'CA10': 'Coin Mechanism',
    'CA11': 'Coin Mechanism',
    'CA13': 'Coin Mechanism',
    'CA14': 'Coin Mechanism',
    'CA15': 'Coin Mechanism',
    'CA17': 'Coin Mechanism',
    'VA1': 'Value of All',
    'EA1': 'Event',
    'EA2': 'Event',
    'EA3': 'Event',
    'EA4': 'Event',
    'EA5': 'Event',
    'EA6': 'Event',
    'EA7': 'Event',
    'PA1': 'Product',
    'PA2': 'Product',
    'PA4': 'Product',
    'LA1': 'Pricelist',
    'DA1': 'Cashless 1',
    'DA2': 'Cashless 1',
    'DA3': 'Cashless 1',
    'DA4': 'Cashless 1',
    'DA5': 'Cashless 1',
    'DA10': 'Cashless 1',
    'DB2': 'Cashless 2',
    'DB3': 'Cashless 2',
    'DB4': 'Cashless 2',
    'DB5': 'Cashless 2',
    'TA2': 'Token Acceptor',
    'TA3': 'Token Acceptor',
    'TA4': 'Token Acceptor',
    'TA5': 'Token Acceptor',
    'TA6': 'Token Acceptor',
    'VA2': 'Value of All..',
    'VA3': 'Value of All..',
    'AM1': 'Audit module',
    'G85': 'Integrity Check',
    'AM1': 'Audit module',
    'SE': 'End of Transmission Set',
    'DXE': 'End of Transaction',
    'XX1': 'Other'
}